// Copyright Recursoft LLC. All Rights Reserved.

#include "Compilers/SMCompilerDelegates.h"

FSMCompilerDelegates::FOnBlueprintCompiledSignature FSMCompilerDelegates::OnStateMachinePreCompiled;
FSMCompilerDelegates::FOnBlueprintCompiledSignature FSMCompilerDelegates::OnStateMachinePostCompiled;
FSMCompilerDelegates::FOnBlueprintCompiledSignature FSMCompilerDelegates::OnNodePreCompiled;
FSMCompilerDelegates::FOnBlueprintCompiledSignature FSMCompilerDelegates::OnNodePostCompiled;
